version: "3.9"

services:
  database:
    container_name: movielens-database
    environment:
      - POSTGRES_DB=movielens
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=''
    image: postgres:14.5
    ports:
      - "5433:5432"
    volumes:
      - movielens-database:/var/lib/postgresql/data

  server:
    build:
      context: .
      args:
        - Dev=true
    container_name: movielens_server
    depends_on:
      - database
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=movielens
      - SQL_USER=postgres
      - SQL_PASSWORD=''
      - SQL_HOST=localhost
      - SQL_PORT=5432

    ports:
      - 8000:8000
    volumes:
      - ./app:/srv
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

volumes:
  movielens-database:
